name: build & deploy to gh-pages

on:
  push:
    branches: [ main ]     # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write      # if you use the official pages action
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Install deps
      run: npm ci

    - name: Build (inject API_KEY)
      run: npm run build
      env:
        API_KEY: ${{ secrets.API_KEY }}

    - name: Prepare publish directory
      run: |
        mkdir public
        cp index.html questions.json style.css script.js public/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public